### ISSUE TITLE
"No connection adapters were found" error

### ISSUE THREAD

**Issue by nahgnaw** [tetherless-world/dco-elasticsearch#12]
I got this error: `requests.exceptions.InvalidSchema: No connection adapters were found for 'localhost:9200/dco/publication/_mapping'` when running `python ingest-publications.py --es localhost:9200 --publish out`. 

What was I missing? @zednis 

The full traceback:

```
Traceback (most recent call last):
  File "ingest-publications.py", line 258, in <module>
    publish(bulk=bulk_str, endpoint=args.es, rebuild=args.rebuild, mapping=args.mapping)
  File "ingest-publications.py", line 209, in publish
    r = requests.put(mapping_url, data=mapping_file)
  File "/Library/anaconda/envs/dco/lib/python3.5/site-packages/requests/api.py", line 122, in put
    return request('put', url, data=data, **kwargs)
  File "/Library/anaconda/envs/dco/lib/python3.5/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/Library/anaconda/envs/dco/lib/python3.5/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/anaconda/envs/dco/lib/python3.5/site-packages/requests/sessions.py", line 567, in send
    adapter = self.get_adapter(url=request.url)
  File "/Library/anaconda/envs/dco/lib/python3.5/site-packages/requests/sessions.py", line 641, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for 'localhost:9200/dco/publication/_mapping'
```

**Comment by zednis** [comment]
It is possible the index does not exist.

What happens when you run the following?

`$ curl -XGET localhost:9200/dco`
`$ curl -XGET localhost:9200/dco/publication`

**Comment by nahgnaw** [comment]
I created an index with
`curl -XPUT 'localhost:9200/dco?pretty'`, 
and now `curl -XGET localhost:9200/dco` has responses. 
But for `curl -XGET localhost:9200/dco/publication`, I still got `{"error":"ElasticsearchIllegalArgumentException[No feature for name [publication]]","status":400}`. 

Do I also need to create "publication" as a type? Which command should I use?

**Comment by am-e** [comment]
If the ingest script ran without issue then the data is probably there.
Try:
curl -XGET localhost:9200/dco/publication/_search

Or:
http://localhost:9200/dco/publication/_search?pretty=true in the browser
- The Elasticsearch Get API requires an ID, as in:

curl -XGET localhost:9200/dco/publication/1015-6779-1645-7537-CC

**Comment by zednis** [comment]
:+1 to @am-e 

If you successfully created a bulk import file you can import it manually without having to re-run the ingest script.

Try this:
`$ curl -XPOST localhost:9200/_bulk --data-binary @file.bulk`

**Comment by nahgnaw** [comment]
I was able to manually import the data using the bulk API.

**Comment by Liumkattan** [comment]
its too late but just in case.
`requests.exceptions.InvalidSchema`
That happens because requests can't figure out the protocol, just add `http://` before the url
