### ISSUE TITLE
Ready to ingest the data on datasets on test server to test dataset browser

### ISSUE THREAD

**Issue by zhongh** [tetherless-world/dco-elasticsearch#14]
Just pushed new commit to the dataset-browser branch. Facets, attributes, especially access and download links of distributions of dataset.

1) It works on my localhost
2) New page created on "http://udco.tw.rpi.edu/vivo/dataset-test". Since the search_url is set to //localhost:9200/dco/publication/_search', this page works when I open it from my machine. (See attached screen shots)
<img width="809" alt="qq20150917-2 2x" src="https://cloud.githubusercontent.com/assets/11859381/9925194/53e6f54c-5cd6-11e5-8dc9-23e81249afa5.png">
<img width="888" alt="qq20150917-1 2x" src="https://cloud.githubusercontent.com/assets/11859381/9925193/53e5e18e-5cd6-11e5-8fa5-33876a4f1568.png">

I am wondering if we can quickly ingest the data to the server, then we can see if it works.

Use "python3 ingest-datasets.py <filename>" to get the data. Default parameters are set. And the mapping file is mappings/dataset.json

**Comment by zednis** [comment]
I think you can remove the "only show DCO contributions" checkbox (and associated hidden facet).  That should also fix the gap in the facets on the side.

**Comment by zednis** [comment]
Also, use CURL to POST the bulk data file to the dcotest elastic search URL and then update the HTML on UDCO to use the dcotest ES.

**Comment by zhongh** [comment]
Just push an update, "only show DCO contributions" and related functions are removed. Page aligned well.

**Comment by zhongh** [comment]
However, I uploaded exactly the same bulk data file and mapping file to both localhost:9200 and dcotest.tw.rpi.edu/search, tried uploading them both manually (CURL) and by the ingest-dataset script, but the browser works when search_url is set to '//localhost:9200/dco/dataset/_search', and doesn't work for '//dcotest.tw.rpi.edu/search/dco/dataset/_search' nor 'https://dcotest.tw.rpi.edu/search/dco/dataset/_search', giving an error message: "Failed to load resource: the server responded with a status of 500 (Internal Server Error)"

The https://dcotest.tw.rpi.edu/search/dco/dataset/_search and https://dcotest.tw.rpi.edu/search/dco/dataset/_mapping display fine though. Very weird.

**Comment by zhongh** [comment]
Problem solved by Patrick:
"Had to go into the docker container on dcotest for elasticsearch and take a look at logs. There were no logs. We need to redirect output from running elasticsearch to a log file
        elasticsearch > es.log 2>&1
Guessed that the error message was in fact related to the elasticsearch cache, that the cache might be corrupt so cleared the elasticsearch cache."
Now it is viewable on "udco.tw.rpi.edu/vivo/dataset-test".
