### ISSUE TITLE
Remove ingest-datasets-old.py

### ISSUE THREAD

**Issue by zednis** [tetherless-world/dco-elasticsearch#36]
Let's remove the now deprecated old dataset ingest script.

**Comment by zhongh** [comment]
Do I need to create a new branch to remove the old dataset ingest script, or just push the deletion to the main branch?

**Comment by zednis** [comment]
Do it in a branch just to make sure.

**Comment by zednis** [comment]
Do we have an update on this?

**Comment by mrpatrickwest** [comment]
There's a branch, it removes the file, and ingest of datasets is working in test and production. So I'm guessing we can merge the branch and close this issue.

**Comment by zednis** [comment]
https://github.com/tetherless-world/dco-elasticsearch/pull/37 is showing a conflict on the proposed merge.  I guess I will attempt to resolve the conflict.
