### ISSUE TITLE
remove citation popover window title

### ISSUE THREAD

**Issue by mrpatrickwest** [tetherless-world/dco-elasticsearch#48]

**Comment by mrpatrickwest** [comment]
branch is remove-popover-title

**Comment by mrpatrickwest** [comment]
reference https://github.com/tetherless-world/dco-citations/issues/16

**Comment by zednis** [comment]
http://stackoverflow.com/questions/11224892/how-do-you-disable-the-title-in-twitter-bootstraps-popover-plugin

**Comment by zednis** [comment]
facetview2 has a local reference to bootstrap 2.0.1 so the best solutions is to add

```
        .popover-title { display: none; }
```

to the CSS style block in publications.html
