### ISSUE TITLE
Be able to close citation popover by clicking anywhere outside the popover

### ISSUE THREAD

**Issue by mrpatrickwest** [tetherless-world/dco-elasticsearch#49]
Reference issue https://github.com/tetherless-world/dco-citations/issues/17

**Comment by zednis** [comment]
"or hitting escape?"

**Comment by mrpatrickwest** [comment]
Suppose that would be a bonus feature ... it's the first thing I did after popping up a citation, hit escape to try to close the popover. I'm going to remove that until someone brings it up.

**Comment by zednis** [comment]
Isn't the ESC key generally interpreted by browsers to mean 'stop loading the webpage'?

**Comment by mrpatrickwest** [comment]
Usually yes ... but there are plenty of websites that I've visited where a popup or overlay or something similar is closed by hitting the escape key. Zillow, Facebook, Linked In, Monster, etc...

**Comment by zhongh** [comment]
A simple way to do it is to have something like:

//        $('html').on('click', function(e) {
//            if (typeof $(e.target).data('toggle') == 'undefined' &&
//                    !$(e.target).parents().is('.popover.in')) {
//                $('[data-toggle]').popover('hide');
//            }
//        });

**Comment by zednis** [comment]
@zhonghao1014 try it locally and if it works create a branch and commit the proposed change to the branch.
